INSERT INTO websites (name, url) VALUES
    ('GitHub', 'https://github.com'),
    ('YouTube', 'https://www.youtube.com'),
    ('Google', 'https://www.google.com'),
    ('Amazon', 'https://www.amazon.com'),
    ('Facebook', 'https://www.facebook.com'),
    ('Instagram', 'https://www.instagram.com'),
    ('X (Twitter)', 'https://x.com'),
    ('Reddit', 'https://www.reddit.com'),
    ('Wikipedia', 'https://www.wikipedia.org'),
    ('Microsoft', 'https://www.microsoft.com'),
    ('Apple', 'https://www.apple.com'),
    ('Netflix', 'https://www.netflix.com'),
    ('Twitch', 'https://www.twitch.tv'),
    ('Discord', 'https://discord.com'),
    ('Spotify', 'https://www.spotify.com'),
    ('Steam', 'https://store.steampowered.com'),
    ('Cloudflare', 'https://www.cloudflare.com'),
    ('Stack Overflow', 'https://stackoverflow.com'),
    ('LinkedIn', 'https://www.linkedin.com'),
    ('WhatsApp', 'https://www.whatsapp.com'),
    ('Zoom', 'https://zoom.us'),
    ('Slack', 'https://slack.com'),
    ('Dropbox', 'https://www.dropbox.com'),
    ('PayPal', 'https://www.paypal.com'),
    ('eBay', 'https://www.ebay.com'),
    ('CNN', 'https://www.cnn.com'),
    ('BBC', 'https://www.bbc.com'),
    ('NYTimes', 'https://www.nytimes.com'),
    ('GitLab', 'https://gitlab.com'),
    ('Bitbucket', 'https://bitbucket.org'),
    ('npm', 'https://www.npmjs.com'),
    ('PyPI', 'https://pypi.org'),
    ('Docker Hub', 'https://hub.docker.com'),
    ('AWS', 'https://aws.amazon.com'),
    ('Azure', 'https://azure.microsoft.com'),
    ('DigitalOcean', 'https://www.digitalocean.com'),
    ('Heroku', 'https://www.heroku.com'),
    ('Vercel', 'https://vercel.com'),
    ('Cloudflare Status', 'https://www.cloudflarestatus.com'),
    ('OpenAI', 'https://openai.com'),
    ('Anthropic', 'https://www.anthropic.com'),
    ('Hacker News', 'https://news.ycombinator.com'),
    ('Medium', 'https://medium.com'),
    ('TikTok', 'https://www.tiktok.com'),
    ('Pinterest', 'https://www.pinterest.com'),
    ('Snapchat', 'https://www.snapchat.com'),
    ('Etsy', 'https://www.etsy.com'),
    ('Shopify', 'https://www.shopify.com'),
    ('WordPress.com', 'https://wordpress.com'),
    ('Mozilla', 'https://www.mozilla.org');
